server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
    discovery:
      locator:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/