server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    uri: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/