server:
  port: 9003

spring:
  application:
    name: notification-service
  
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PWD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/